"""Added more fields to improve Product metadata And CategoryModel

Revision ID: 29805eb517a6
Revises: f8122a8a72f1
Create Date: 2024-08-16 11:17:23.291915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29805eb517a6'
down_revision: Union[str, None] = 'f8122a8a72f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('trending_score', sa.Float(), nullable=True),
    sa.Column('popularity_index', sa.Float(), nullable=True),
    sa.Column('user_interest_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('color', sa.String(), nullable=True))
    op.add_column('products', sa.Column('material', sa.String(), nullable=True))
    op.add_column('products', sa.Column('size', sa.String(), nullable=True))
    op.add_column('products', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('products', sa.Column('sku', sa.String(), nullable=True))
    op.add_column('products', sa.Column('image_urls', sa.String(), nullable=True))
    op.add_column('products', sa.Column('video_url', sa.String(), nullable=True))
    op.add_column('products', sa.Column('three_d_model_url', sa.String(), nullable=True))
    op.add_column('products', sa.Column('ar_url', sa.String(), nullable=True))
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index('ix_products_description', table_name='products')
    op.drop_index('ix_products_name', table_name='products')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.alter_column('user_interactions', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_user_interactions_product_id', table_name='user_interactions')
    op.drop_index('ix_user_interactions_user_id', table_name='user_interactions')
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.create_index('ix_user_interactions_user_id', 'user_interactions', ['user_id'], unique=False)
    op.create_index('ix_user_interactions_product_id', 'user_interactions', ['product_id'], unique=False)
    op.alter_column('user_interactions', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_index('ix_products_name', 'products', ['name'], unique=False)
    op.create_index('ix_products_description', 'products', ['description'], unique=False)
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('products', 'ar_url')
    op.drop_column('products', 'three_d_model_url')
    op.drop_column('products', 'video_url')
    op.drop_column('products', 'image_urls')
    op.drop_column('products', 'sku')
    op.drop_column('products', 'brand')
    op.drop_column('products', 'weight')
    op.drop_column('products', 'size')
    op.drop_column('products', 'material')
    op.drop_column('products', 'color')
    op.drop_column('products', 'category_id')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
