"""Added ProductStockModel, WarehouseModel and upgraded existing Models

Revision ID: 80e5e0aa9560
Revises: 29805eb517a6
Create Date: 2024-09-30 14:47:11.672193

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80e5e0aa9560'
down_revision: Union[str, None] = '29805eb517a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Define the Enum type for category_type
categorytype = sa.Enum('STANDARD', 'TRENDING', 'AI_RECOMMENDED', name='categorytype')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the Enum type first
    categorytype.create(op.get_bind(), checkfirst=True)

    # Create the warehouses table
    op.create_table('warehouses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('location', sa.String(), nullable=False),
        sa.Column('vendor_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)

    # Create the product_stock table
    op.create_table('product_stock',
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('warehouse_id', sa.Integer(), nullable=False),
        sa.Column('stock', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
        sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
        sa.PrimaryKeyConstraint('product_id', 'warehouse_id')
    )

    # Add the new category_type column with the Enum type
    op.add_column('categories', sa.Column('category_type', categorytype, nullable=True))

    # Add new fields to products table
    op.add_column('products', sa.Column('is_in_stock', sa.Boolean(), nullable=False, server_default=sa.sql.expression.true()))
    op.add_column('products', sa.Column('total_stock', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop the added columns in downgrade
    op.drop_column('products', 'total_stock')
    op.drop_column('products', 'is_in_stock')
    op.drop_column('categories', 'category_type')

    # Drop the product_stock and warehouses tables
    op.drop_table('product_stock')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_table('warehouses')

    # Drop the Enum type in downgrade
    categorytype.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
